## This file contains the configuration for the training process

# Directory paths
trainer_params:
  train_dir: './data/'    # Location images and masks for training. Two subdirectories are expected: 'source' and 'mask'
  models_dir: './data/models/state_weights/'   # Location to save the trained models
  input_size: 256               # Size of the input images (increase due to stiching time)
  precision: 'float'            # Precision of the model (float or half)

# Training parameters
model_params:
  previous_weights: null        # Path to previous weights to continue training
  pooling_steps: 4              # Number of pooling steps in the model

# Data import parameters
data_params:
  batch_size: 1                 # Batch size for training
  num_workers: 2                # Number of workers for the DataLoader class (load images in parallel), currently not working
  subsetting: 5                 # Percentage of the training data to use or number of images to subset
  filter_threshold: 0.25        # Threshold to filter out images with low mask coverage
  val_ratio: .33                # Validation ratio (percentage of data to use for validation)

# Optimizer parameters (common names, so no explanation needed)
optimizer_params:
  num_epochs: 21
  model_name: 'unet_model_test_4'
  verbose: true
  learning_rate: 0.003
  gamma: 0.1
  step_size: 7
