## This file contains the configuration for the training process

# Directory paths
trainer_params:
  binary_segmentation: true             # Whether the segmentation map contains multiple classes or not
  model_settings: './top_models.json'   # Location to save the trained models
  num_epochs: 25
  debugging: false
  verbose: true
  early_stop_patiente: 5

# Data import parameters
dataset_params:
  source_dir: './data/source'                   # Location images and masks for training. Two subdirectories are expected: 'source' and 'mask'
  masks_dir: './data/masks_cleaned'    # Location images and masks for training. Two subdirectories are expected: 'source' and 'mask'
  n_patches: 25                                  # Batch size for training
  val_ratio: .2                                 # Validation ratio (percentage of data to use for validation)
  input_size: 256               # Size of the input images (increase due to stiching time)

# Optimizer parameters (common names, so no explanation needed)
optimizer_params:
  learning_rate: 0.003
  gamma: 0.1
  step_size: 10
